name: 'Kichijojisteve '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5354457
title: 'Various Thoughts '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140a09'
    - '#fe464e'
    - '#a29a87'
    - '#fffffa'
    - '#5c5543'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
