title: 'Various Thoughts '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9232008
  brandStrength: 0.5
  lightness: 0.5590762
  brandColors:
    - '#140a09'
    - '#fe464e'
    - '#a29a87'
    - '#fffffa'
    - '#5c5543'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Kichijojisteve '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5354457
layout_spectrum: 1
