layout_spectrum: 1
typography_spectrum: 0.5354457
color:
  saturation: 0.9837404
  lightness: 0.4073864
  brandStrength: 0.6191515
  rhythmicContrast: 0.8007546
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'Kichijojisteve '
